language: bash
services: docker

env:
  - VERSION=0.11 PYTHON_VERSION=2.7 VARIANT=slim
  - VERSION=0.11 PYTHON_VERSION=3.6 VARIANT=slim
  - VERSION=0.11 PYTHON_VERSION=3.7 VARIANT=slim
  - VERSION=0.11 PYTHON_VERSION=2.7 VARIANT=alpine
  - VERSION=0.11 PYTHON_VERSION=3.6 VARIANT=alpine
  - VERSION=0.11 PYTHON_VERSION=3.7 VARIANT=alpine
  - VERSION=0.12 PYTHON_VERSION=2.7 VARIANT=slim
  - VERSION=0.12 PYTHON_VERSION=3.6 VARIANT=slim
  - VERSION=0.12 PYTHON_VERSION=3.7 VARIANT=slim
  - VERSION=0.12 PYTHON_VERSION=2.7 VARIANT=alpine
  - VERSION=0.12 PYTHON_VERSION=3.6 VARIANT=alpine
  - VERSION=0.12 PYTHON_VERSION=3.7 VARIANT=alpine
  - VERSION=1.0 PYTHON_VERSION=2.7 VARIANT=slim
  - VERSION=1.0 PYTHON_VERSION=3.6 VARIANT=slim
  - VERSION=1.0 PYTHON_VERSION=3.7 VARIANT=slim
  - VERSION=1.0 PYTHON_VERSION=2.7 VARIANT=alpine
  - VERSION=1.0 PYTHON_VERSION=3.6 VARIANT=alpine
  - VERSION=1.0 PYTHON_VERSION=3.7 VARIANT=alpine

script:
  - ./scripts/cibuild

deploy:
  - provider: script
    script: "scripts/cipublish"
    on:
      repo: azavea/docker-flask
      branch: master
