FROM python:%%PYTHON_VERSION%%-slim

MAINTAINER Azavea <systems@azavea.com>

COPY requirements.txt /tmp/

RUN set -ex \
    && buildDeps=" \
       g++ \
       gcc \
    " \
    && apt-get update && apt-get install -y ${buildDeps} --no-install-recommends \
    && pip install --no-cache-dir -r /tmp/requirements.txt \
    && apt-get purge -y --auto-remove ${buildDeps} \
    && rm -rf /tmp/requirements.txt /var/lib/apt/lists/*

ENTRYPOINT ["/usr/local/bin/gunicorn"]
